# Dependencies
markdown:         redcarpet
highlighter:         'pygments'

# Permalinks
permalink:        pretty

# Setup
title:            Jarcoal
tagline:          'A Jekyll theme'
description:      'Go, Python and Portland'
url:              https://github.com/jarcoal

author:
  name:           'Jared Morse'
  url:            https://github.com/jarcoal

paginate:         5